CREATE TABLE IF NOT EXISTS `UNISYS`.`FACULTIES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `UNISYS`.`COURSES` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(500) NULL,
  `FACULTY_ID` INT NOT NULL,
  `CREDIT_REWARD` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_COURSE_FACULTY_idx` (`FACULTY_ID` ASC) VISIBLE,
  UNIQUE INDEX `CREDIT_REWARD_UNIQUE` (`CREDIT_REWARD` ASC) VISIBLE,
  CONSTRAINT `FK_COURSE_FACULTY`
    FOREIGN KEY (`FACULTY_ID`)
    REFERENCES `UNISYS`.`FACULTIES` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `UNISYS`.`STUDENTS` (
  `FACULTY_NUMBER` INT UNSIGNED NOT NULL,
  `FIRST_NAME` VARCHAR(150) NOT NULL,
  `FULL_NAME` VARCHAR(300) NOT NULL,
  `CREDITS` INT NOT NULL DEFAULT 0,
  `FACULTY_ID` INT NOT NULL,
  PRIMARY KEY (`FACULTY_NUMBER`),
  UNIQUE INDEX `FACULTY_NUMBER_UNIQUE` (`FACULTY_NUMBER` ASC) VISIBLE,
  INDEX `FK_STUDENT_FACULTY_idx` (`FACULTY_ID` ASC) VISIBLE,
  CONSTRAINT `FK_STUDENT_FACULTY`
    FOREIGN KEY (`FACULTY_ID`)
    REFERENCES `UNISYS`.`FACULTIES` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB